export { AppIcon } from './app-icon';
export { GoogleIcon } from './socials/google';
export { FacebookIcon } from './socials/facebook';
export { AppleIcon } from './socials/apple';
export { XIcon } from './socials/x';
export { ShieldIcon } from './shield';
export { FingerprintIcon } from './fingerprint';
export { WarningIcon } from './warning';
export { HomeIcon } from './tabs/home';
export { DiscoverIcon } from './tabs/discover';
export { Arrow } from './arrow';
export { HistoryIcon } from './tabs/history';
export { SendIcon } from './send';
export { SwapIcon } from './swap';
export { ReceiveIcon } from './receive';
export { SwapOppositeArrowsIcon } from './swap-oposite-arrows';
export { ArrowBottomFilledIcon } from './arrow-bottom-filled';
export { CloseIcon } from './close';
export { SettingsFilledIcon } from './settings-filled';
export { InfoIcon } from './info';
export { CheckboxCircle } from './chekbox-circle';
export { SuccessIconWrapped } from './sucess-icon-wrapped';
export { ArrowWithTail } from './arrow-with-tail';
export { GearIcon } from './gear-icon';
export { ChartArrow } from './chart-arrow';

export * from './settings';
